# Generated by Django 4.2.16 on 2025-06-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_message_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='available_rooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hostel',
            name='total_rooms',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
