# Generated by Django 4.2.16 on 2025-06-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='hostels/images/')),
                ('description', models.TextField()),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('rooms_available', models.IntegerField(default=0)),
                ('gender_restriction', models.CharField(choices=[('unisex', 'Unisex'), ('male_only', 'Male Only'), ('female_only', 'Female Only')], default='unisex', max_length=50)),
                ('has_security', models.BooleanField(default=False)),
                ('has_water', models.BooleanField(default=False)),
                ('has_power', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('amenities', models.TextField(blank=True, null=True)),
                ('town', models.CharField(blank=True, max_length=100, null=True)),
                ('university_nearby', models.CharField(blank=True, max_length=255, null=True)),
                ('distance_to_campus', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.FloatField(blank=True, default=0.0, null=True)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
